### ISSUE TITLE
Merge back into https://github.com/czzarr/node-bitwise-xor

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/buffer-xor#1]
We should ask @czzarr if we can merge this into his repo or vice versa.
Didn't find it on my first search.  Clearly need to get better at that.

We'd want to fix his version to be more performant though, where as right now it uses twice as much memory as necessary.

**Comment by czzarr** [comment]
Hi, just saw this, what exactly do you want to do ?

**Comment by dcousens** [comment]
@czzarr basically take the code that is here,  and merge it into your library.

The differences between this library and yours:

* `/inline` for inline xor w/o creating a `new Buffer`
* Faster performance due to not creating an intermediate `Array`
* Supports `Buffer` input only, no defaulting to `utf8` strings (happy to change this, but we should probably add an encoding option then)
* Increased testing coverage

**Comment by czzarr** [comment]
I don't really see the point of having two different modules with the same code. They have different features, people can chose one or the other depending on their needs. Freedom of choice :)

**Comment by dcousens** [comment]
@czzarr I don't intend to have two modules. My question was, can we merge the code here into yours, given the above changes?  Would you be open to that?

**Comment by dcousens** [comment]
Bump @czzarr

**Comment by dcousens** [comment]
@czzarr?

**Comment by dcousens** [comment]
another bump @czzarr

**Comment by czzarr** [comment]
Hi @dcousens, sorry for the late reply. To be honest I'd rather keep mine as is. As I said earlier, your feature set is not the same as mine, that's why we need two different modules.

**Comment by dcousens** [comment]
No worries.
Thanks for the reply @czzarr
