### ISSUE TITLE
xoring until the smaller buffer ends is not semantically correct

### ISSUE THREAD

**Issue by dbkaplun** [crypto-browserify/buffer-xor#2]
In theory you can xor two whole numbers of any size. Since there is a natural, one-to-one mapping between whole numbers and buffers, it makes sense that the xor operation can and should be preserved across the mapping. That means that, when applied to `Buffer`s, it should treat the shorter array as if it was padded with `0`s to the longer array's length, instead of ignoring the longer array's extra data. This is the [implementation on current master](https://github.com/crypto-browserify/buffer-xor/blob/8f92b79a8b8133c26a7ae1af09b2c84ec6e3f426/index.js):
```js
module.exports = function xor (a, b) {
  var length = Math.min(a.length, b.length)
  var buffer = new Buffer(length)

  for (var i = 0; i < length; ++i) {
    buffer[i] = a[i] ^ b[i]
  }

  return buffer
}
```

It should look more like:
```js
module.exports = function xor (a, b) {
  var length = Math.max(a.length, b.length)
  var buffer = new Buffer(length)

  for (var i = 0; i < length; ++i) {
    buffer[i] = (a[i] || 0) ^ (b[i] || 0) // unoptimized, mathematically sound xor
  }

  return buffer
}
```

Hope that's clear. Let me know if that doesn't make sense. Thanks!

**Comment by fanatid** [comment]
@dbkaplun `a[i] | 0` is faster than `a[i] || 0`, `x ^ undefined` = `x ^ 0` = `x`

optimized version with max:
```js
module.exports = function xor (a, b) {
  if (a.length >= b.length) {
    a = new Buffer(a)
  } else {
    var t = a
    a = new Buffer(b)
    b = t
  }

  for (var i = 0; i < b.length; ++i) a[i] ^= b[i]
  return a
}
```

**Comment by dcousens** [comment]
> That means that, when applied to Buffers, it should treat the shorter array as if it was padded with 0s to the longer array's length, instead of ignoring the longer array's extra data. 

I'm not sure I understand your reasoning behind this?

**Comment by dbkaplun** [comment]
@dcousens because numbers are represented this way when they are xored.

Consider the expression 15 ^ 3. It can be calculated like so:

* 15 ^ 3 = 1111b ^ 11b (xor operates on binary digits, so we convert each number to binary)
* 1111b ^ 0011b (pad with 0s in preparation for xor. 11b is equivalent to 0011b)
* perform bitwise xor for each binary digit to achieve 1100b = 12. Node confirms this. (Note that a ^ 0 = a for any number or binary digit.)

In the same same way we are performing xor on Buffers, which are really just memory-efficient representations of numbers. The only difference is that our current implementation crops the buffers, meaning that the 15 ^ 3 example would come out to 11b ^ 11b = 0. So it is clearly more correct to xor excess buffer indices with 0 than to drop them altogether.

**Comment by dcousens** [comment]
Of course.

I agree with this :+1:
